export type Status = "confirmed" | "must" | "recommended" | "none";
export type Item = { title:string; detail:string; status?:Status; link?:string; linkLabel?:string };
export type Day = { date:string; weekday:string; city:string; title:string; summary:string; hotel:string; itinerary:Item[]; transport:Item[]; luggage:Item[]; food:Item[]; hotels:Item[]; bookings:Item[] };
const i=(title:string,detail:string,status?:Status,link?:string,linkLabel="打开官网"):Item=>({title,detail,status,link,linkLabel});

export const days:Day[] = [
{date:"10.10",weekday:"周六",city:"东京",title:"抵达东京 · 轻轻落地",summary:"15:00 抵达 NRT。今晚不给时差添任务，只安排一段城市散步和一顿舒服的第一餐。",hotel:"东京王子大饭店 · 第 1 晚",itinerary:[i("15:00｜抵达成田机场","入境、取行李、ATM / Welcome Suica 预留约 90–120 分钟。"),i("18:00｜入住与散步","入住东京王子大饭店；有精神就沿芝公园、增上寺与东京塔周边短走，不再跨城赶景点。")],transport:[i("N’EX 成田特快","直达东京、涩谷、新宿；航班延误时改下一班更灵活。普通指定席通常提前 1 个月开售。","recommended","https://www.jreast.co.jp/en/multi/nex/tickets/","JR 东日本"),i("备选：Skyliner","若住上野 / 浅草更顺路，京成 Skyliner 到日暮里、上野。","recommended","https://www.keisei.co.jp/keisei/tetudou/skyliner/us/","京成电铁")],luggage:[i("全部随身进城","今晚把大箱与 2 晚小包分开；小包准备松本、上高地、高山所需。","none")],food:[i("Tokyo comfort-food night","烧鸟、刺身、关东煮或拉面；不把高价 omakase 放在长途飞行后的第一晚。")],hotels:[i("东京王子大饭店｜BOOKED / CONFIRMED","Tokyo Prince Hotel，3-3-1 Shibakoen, Minato City, Tokyo；连续入住 10/10 与 10/11 两晚。御成门站 A1 约 1 分钟，大门站 A6 约 7 分钟，JR 滨松町站约 10 分钟步行。","confirmed","https://www.princehotels.com/tokyo/location/","酒店官方交通页")],bookings:[i("机场进城车票","建议订；如果担心入境耗时，可到站购买。","recommended")]},
{date:"10.11",weekday:"周日",city:"东京",title:"江户东京 · 从市场吃到老街",summary:"把东京的旧时气息串成一条线：筑地 / 丰洲的鱼鲜、清澄白河咖啡、浅草与合羽桥。",hotel:"东京王子大饭店 · 第 2 晚",itinerary:[i("08:00｜筑地场外","玉子烧、海鲜小碗与现烤物，避开单店长队，少量多吃。"),i("10:30｜清澄庭园与清澄白河","庭园慢走，再选一家烘焙咖啡馆。"),i("14:00｜浅草寺 → 合羽桥","雷门、仲见世后逛厨具街；傍晚从隅田川侧看东京晴空塔。")],transport:[i("地铁一日移动","IC 卡按次乘坐即可；不必为短途买通票。","none")],luggage:[i("今晚交运大箱","请东京王子大饭店前台用宅急便寄往 10/14 金泽酒店，指定 10/14 到达；在运单写英文姓名、入住日、预订号。至少留 2 天缓冲。","must","https://faq-en.kuronekoyamato.co.jp/app/answers/detail/a_id/6074/","Yamato 酒店互寄说明")],food:[i("午餐：江户前寿司 / 天妇罗","把一顿认真午餐放在今天；热门小店建议预约。","recommended"),i("晚餐：鳗鱼或寿喜烧","浅草老铺很多；若选名店，提前通过官网或酒店礼宾订。","recommended")],hotels:[i("东京王子大饭店｜BOOKED / CONFIRMED","同一酒店连住第二晚；今晚完成退房前整理，并把 Azusa QR voucher 截图离线保存。","confirmed","https://www.princehotels.com/tokyo/location/","酒店官方交通页")],bookings:[i("东京餐厅","高端寿司、天妇罗或寿喜烧建议提前 4–8 周。","recommended")]},
{date:"10.12",weekday:"周一",city:"东京 → 松本",title:"已订 Azusa · 黑城与信州味",summary:"08:00 从东京王子大饭店出发，留足新宿站内寻路时间；10:00 乘已确认的 Azusa，12:37 抵达松本。",hotel:"松本 · 1 晚",itinerary:[i("07:45｜退房完成","早餐、退房与洗手间都在此时前完成；只带 2 晚小旅行包，把 QR voucher、证件与充电宝放在随手可取处。"),i("08:00｜离开东京王子大饭店","低压力主路线：步行约 10 分钟到 JR 滨松町站，从北口进站。搭山手线外回（品川・涩谷方向）直达新宿，车上约 25 分钟，不换车。"),i("08:45–09:00｜抵达新宿 JR 区域","下车后不出 JR 闸机，跟随 Chūō Line / Limited Express 指示与当天电子屏找 Azusa；为站内步行、确认站台、买水和从容上车预留约 60 分钟。"),i("10:00–12:37｜Limited Express Azusa","BOOKED / CONFIRMED：新宿 10:00 → 松本 12:37；2 位成人，Green Reserved，总价 ¥27,560，QR voucher。","confirmed","https://www.jreast.co.jp/en/multi/traininformation/azusa_kaiji/index.html","JR 东日本 Azusa"),i("14:00｜松本城","抵达后先寄存小包并午餐；天守内部楼梯陡，把 60–90 分钟留给城内与护城河。","recommended","https://www.matsumoto-castle.jp/lang/","松本城官网")],transport:[i("推荐｜JR 滨松町 → 新宿","门到 JR 候车区域约 45–60 分钟：酒店→滨松町步行约 10 分钟；山手线外回直达约 25 分钟；新宿站内再留 10–15 分钟。列车换乘 0 次，街面步行约 10 分钟，站内步行中等；全程留在 JR 系统，最少迷路。","none","https://timetables.jreast.co.jp/en/timetable/list1248.html","JR 滨松町官方时刻 / 方向"),i("少走路备选｜大门 → 新宿","酒店步行约 7 分钟到大门站 A6，搭都营大江户线直达新宿，车上约 16 分钟、0 次换车；但大江户线站台较深，抵达后需从都营区域走到 JR Limited Express 区域。","none","https://www.kotsu.metro.tokyo.jp/eng/document/main_route_map_eng.pdf","都营地铁官方线路图"),i("Taxi backup｜直达 JR 新宿站","遇大雨、地铁异常或不想站内转行时，请前台叫车并指定 JR Shinjuku Station South Exit。建议最晚 08:15–08:20 离店；平日早高峰按约 25–40 分钟、¥4,000–¥6,000 预留，堵车时可能更久。目标仍是 09:00 前到 JR 区域。","recommended","https://www.google.com/maps/dir/?api=1&origin=Tokyo+Prince+Hotel&destination=JR+Shinjuku+Station+South+Exit&travelmode=driving","打开地图"),i("同日 fallback｜仅在已订列车不可用时","截图列出的备选：09:00 新宿→11:39 松本；11:00→13:35；12:00→14:35。当前 10:00→12:37 已确认，不需要主动改车。","none")],luggage:[i("只带 2 晚小包","大箱已由东京王子大饭店前台寄往金泽。薄羽绒 / 抓绒、雨衣、两套换洗和充电器不要漏。","none")],food:[i("信州荞麦","先尝冷荞麦，感受本地香气；可搭山葵、野菜天妇罗。"),i("山贼烧与当地清酒","蒜香酱油腌鸡大块炸制，是松本很有代表性的下酒菜。")],hotels:[i("松本站步行圈酒店","优先：靠车站、可寄存行李、早晨易等 10/13 私人团接送。"),i("美之原温泉（备选）","更有旅馆气氛，但次日 08:00 TABINO HOTEL Lit MATSUMOTO 接送安排不适用。")],bookings:[i("Azusa 10:00 新宿 → 12:37 松本｜BOOKED / CONFIRMED","2 位成人；Green Reserved；总价 ¥27,560；QR voucher。出发前确认二维码能离线打开，并以当天站内电子屏为准找站台。","confirmed","https://www.jreast.co.jp/en/multi/traininformation/azusa_kaiji/index.html","JR 东日本 Azusa"),i("新宿站缓冲","08:00 离店，目标 09:00 前进入 JR 区域，为 10:00 发车留约 60 分钟。","none","https://www.jreast.co.jp/en/e/stations/e866.html","JR 新宿站地图")]},
{date:"10.13",weekday:"周二",city:"上高地 → 高山",title:"私人上高地导览 · 穿越至高山",summary:"08:00 从松本酒店出发，参加已确认的私人上高地一日游；按与 vendor 确认的定制安排在上高地巴士总站结束，再自行经平汤前往高山。",hotel:"高山 · 1 晚",itinerary:[i("08:00｜松本酒店接送","TABINO HOTEL Lit MATSUMOTO，1 Chome-4-5 Fukashi, Matsumoto, Nagano。请提前在大堂等候；2 位成人。","confirmed"),i("08:00–约 16:00｜上高地私人导览","GetYourGuide：Kamikochi Private car tour Pickup from Nagano/Matsumoto。约 8 小时，英语；私人车辆与英语司机已包含，实际景点与步行节奏由当天 guide 安排。","confirmed","https://www.getyourguide.com/nagano-l5079/from-nagano-kamikochi-private-day-trip-with-pickup-t1411016/","查看 GetYourGuide 行程"),i("行程结束｜上高地巴士总站","CUSTOM DROP-OFF CONFIRMED WITH VENDOR：不按 voucher 的标准安排返回松本；vendor 已确认可在 Kamikochi Bus Terminal 结束 / 下车。","confirmed"),i("傍晚｜上高地 → 平汤 → 高山","tour 结束后自行购买公交票并换乘；当晚继续入住原定高山酒店。")],transport:[i("上高地 → 平汤温泉｜无需预约","2026 官方时刻：每 30 分钟一班，15:30→15:55、16:00→16:25、16:30→16:55、17:00→17:25、17:30→17:55；从上高地巴士总站 5 号站台出发。建议按 tour 实际结束时间选车。","none","https://www.alpico.co.jp/traffic/local/kamikochi/hirayu/","ALPICO 2026 官方时刻"),i("平汤温泉 → 高山｜无需预约","2026 傍晚班次：16:30→17:31、17:30→18:31。稳妥衔接：16:00 上高地→16:25 平汤，留足换乘缓冲后乘 17:30→18:31 高山；若 15:30 前结束，也可 15:30→15:55 后接 16:30→17:31。","none","https://www.nouhibus.co.jp/route_bus/kamikochi-line-en/","浓飞巴士 2026 官方时刻"),i("后续车票不包含在 tour 内","上高地→平汤与平汤→高山两段均需自行购票；两段官方均标注无需预约。到站后确认售票方式、站台与当天运行状态。","none","https://www.nouhibus.co.jp/route_bus/kamikochi-line-en/","浓飞巴士官方")],luggage:[i("小包随身","大箱已寄往金泽。把护照、药物、贵重品、充电宝与保暖防雨层随身带；无需拖箱进入上高地。","none")],food:[i("午餐自理","午餐与个人消费不含在 tour 价格内；可按 guide 安排在上高地用简餐。"),i("高山夜：飞驒牛","预计最晚 18:31 左右抵达高山；晚餐不要订得过早。","recommended")],hotels:[i("高山酒店｜保留原预订","本日不返回松本；经平汤抵达高山后入住原定酒店。","confirmed")],bookings:[i("上高地私人团｜已预订 / 已确认","Confirmed order；2 位成人；英语；总价 US$373.26。包含私人 tour vehicle + English-speaking driver；不包含午餐、个人消费及上高地→平汤→高山公交票。","confirmed","https://www.getyourguide.com/nagano-l5079/from-nagano-kamikochi-private-day-trip-with-pickup-t1411016/","GetYourGuide"),i("装备与取消政策","穿舒适步行鞋与衣物，并带适合当天山地天气的保暖 / 防雨层。若需取消，须在 10/12 08:00 前操作方可全额退款。"),i("定制下车安排","CUSTOM DROP-OFF CONFIRMED WITH VENDOR：以 vendor 单独确认的上高地巴士总站结束方案为准；voucher 所列返回松本是标准流程，不是当前计划。","confirmed"),i("飞驒牛晚餐","热门烧肉店建议提前 2–4 周；按 18:31 左右抵达高山留缓冲。","recommended")]},
{date:"10.14",weekday:"周三",city:"白川乡 → 金泽",title:"合掌村与北陆第一餐",summary:"早晨高山古街，随后坐预约巴士到白川乡；寄存小包游村，再继续去金泽与大箱会合。",hotel:"金泽 · 1 晚",itinerary:[i("07:30｜宫川朝市与古街","早晨人少，尝飞驒牛握寿司、味噌烤物。"),i("10:00 前后｜高山 → 白川乡","以实际 2026 秋季时刻为准，至少提前 20 分钟到站。"),i("12:00｜白川乡","巴士站寄存行李；先去展望台，再走和田家周边与水渠小路。","recommended","https://shirakawa-go.gr.jp/en/","白川乡观光协会"),i("16:00 前后｜白川乡 → 金泽","预约巴士继续北上；入住后取回大箱。")],transport:[i("高山 → 白川乡 → 金泽","部分班次为预约制且很快售罄；建议把两段一次订好，通常提前 1 个月开放。","must","https://www.nouhibus.co.jp/highwaybus/toyama_en/","浓飞巴士官方")],luggage:[i("白川乡寄存小包","站旁储物柜 / 行李房可能满，抵达后先处理。"),i("金泽酒店领取大箱","前台报姓名与入住信息；若未到，立刻用运单号追踪。")],food:[i("白川乡：朴叶味噌","味噌在朴叶上烤，适合配米饭；也可选飞驒牛可乐饼。"),i("金泽：香箱蟹季前的海鲜","10 月重点吃甘虾、喉黑鱼、加能屋蔬菜和本地寿司。","recommended")],hotels:[i("Hyatt Centric Kanazawa","金泽站西口，餐饮完整。","recommended","https://www.hyatt.com/hyatt-centric/en-US/kmqct-hyatt-centric-kanazawa"),i("Hyatt House Kanazawa","同样贴近车站，空间与洗衣对长途旅行友好。","recommended","https://www.hyatt.com/hyatt-house/en-US/kmqxk-hyatt-house-kanazawa")],bookings:[i("两段高速巴士","9/14 起通常可订；务必核对两段日期与人数。","must"),i("金泽寿司晚餐","热门柜台建议 4–8 周。","recommended")]},
{date:"10.15",weekday:"周四",city:"金泽 → 京都",title:"兼六园清晨 · 穿越北陆",summary:"上午看金泽最精华的庭园和市场，午后经敦贺换乘去京都。",hotel:"京都 · 第 1 晚",itinerary:[i("07:30｜兼六园与金泽城","清晨光线和人流最好；从霞之池走到金泽城石川门。","none","https://www.pref.ishikawa.jp/siro-niwa/kenrokuen/e/","兼六园官网"),i("10:30｜近江町市场","海鲜丼不必只追网红店，也可拆成烤物、寿司与水果。"),i("13:30｜金泽 → 敦贺 → 京都","北陆新干线到敦贺，同站换 Thunderbird；预留换乘余量。"),i("17:30｜鸭川 / 先斗町","入住后散步，正式京都晚餐。")],transport:[i("北陆新干线 + Thunderbird","金泽至京都需在敦贺换乘；两段建议一起订指定席。JR-WEST 通常提前 1 个月开放。","must","https://www.westjr.co.jp/global/en/howto/train-reservation/condition/","JR-WEST 预约"),i("HOKURIKU One-way Ticket","访日游客可比较官方单程优惠票，适用条件与取票规则需在购买页确认。","recommended","https://www.westjr.co.jp/travel-information/en/tickets-passes/oneway/hokuriku/","JR-WEST 优惠票")],luggage:[i("大箱随人去京都","两段列车不适用东海道新干线 >160 cm 强制预约规则，但换乘时仍应轻装、看好行李。")],food:[i("近江町：海鲜早餐 / 午餐","甘虾、喉黑鱼与本地贝类优先。"),i("京都：割烹或蔬菜料理","第一晚适合一顿预约制京都料理。","recommended")],hotels:[i("Hyatt Regency Kyoto","东山七条，靠近三十三间堂与清水寺南侧。","recommended","https://www.hyatt.com/hyatt-regency/en-US/kyoto-hyatt-regency-kyoto"),i("Park Hyatt Kyoto","二年坂位置无可替代，适合把酒店本身当体验。","recommended","https://www.hyatt.com/park-hyatt/en-US/itmph-park-hyatt-kyoto"),i("Hyatt Place Kyoto","地铁丸太町旁，实用且交通便利。","recommended","https://www.hyatt.com/hyatt-place/en-US/itmzk-hyatt-place-kyoto")],bookings:[i("金泽→京都列车","9/15 起通常可购。","must"),i("京都料理","高端割烹 / 怀石建议 1–2 个月。","recommended")]},
{date:"10.16",weekday:"周五",city:"京都",title:"东山 · 寺院与小巷的清晨",summary:"用早起换来安静的清水寺，沿保存最好的东山街巷一路走到祇园。",hotel:"京都 · 第 2 晚",itinerary:[i("07:00｜清水寺","早到避开旅行团；舞台、地主神社周边与音羽瀑布。","none","https://www.kiyomizudera.or.jp/en/","清水寺官网"),i("09:00｜三年坂 → 二年坂","店铺开门前更适合看街景，之后转高台寺。"),i("13:30｜建仁寺 / 祇园","留出一段无目标漫步，白川南通傍晚最美。"),i("18:00｜预约晚餐","把最期待的一顿京都料理放今晚。")],transport:[i("公交 + 步行","清早可出租车到清水寺；白天东山路堵，步行更可靠。","none")],luggage:[i("酒店内不移动","把下一次宅配运单所需的东京酒店地址准备好。","none")],food:[i("早餐：汤豆腐 / 日式早餐","东山的好早餐选择不多，热门店建议预约。","recommended"),i("晚餐：怀石 / 割烹","尊重到店时间与取消政策；如有过敏务必提前告知。","must")],hotels:[i("续住京都酒店","三晚不换房。")],bookings:[i("京都高端晚餐","建议现在就订；许多店通过酒店礼宾或 TableCheck。","must","https://www.tablecheck.com/en/japan","TableCheck") ]},
{date:"10.17",weekday:"周六",city:"奈良",title:"奈良日归 · 古寺与柿叶寿司",summary:"早去奈良公园，从春日大社、若草山脚到东大寺；傍晚回京都。",hotel:"京都 · 第 3 晚",itinerary:[i("08:00｜京都 → 奈良","JR 或近铁都可；酒店位置决定哪条更顺。"),i("09:00｜春日大社","从石灯笼参道慢慢进入森林。","none","https://www.kasugataisha.or.jp/en/about_en/","春日大社"),i("11:30｜奈良町午餐","柿叶寿司、葛料理或茶粥。"),i("14:00｜东大寺","大佛殿与南大门；周六人多，午后稍缓。","none","https://www.todaiji.or.jp/en/","东大寺"),i("17:00｜返回京都","最后一晚整理行李。")],transport:[i("京都 ↔ 奈良","普通列车班次多，不需预约；ICOCA / Suica 可用。","none")],luggage:[i("今晚打包","大箱明早从京都寄往 10/19 东京酒店；箱根仅带一晚包。")],food:[i("奈良：柿叶寿司、葛、茶粥","柿叶寿司很适合做轻午餐；志津香釜饭常排长队，不要让排队绑架行程。"),i("京都最后一晚：居酒屋","把正式怀石留给前一晚，今晚吃季节小菜与清酒。","recommended")],hotels:[i("续住京都酒店","今晚确认前台明早宅配截单时间。")],bookings:[i("奈良主要寺社","通常现场购票即可。","none")]},
{date:"10.18",weekday:"周日",city:"京都 → 箱根",title:"向东而行 · 温泉之夜",summary:"早上把大箱送走，乘新干线到小田原，进入箱根完成半程环线，晚上泡温泉吃会席。",hotel:"箱根 · 1 晚",itinerary:[i("08:00｜京都站出发","Hikari 直达小田原最省转车；若班次不合适，在名古屋换乘。"),i("11:00｜小田原 → 箱根","购买 / 启用箱根周游券，按天气决定先走大涌谷还是芦之湖。"),i("13:00｜强罗 / 大涌谷","缆车会因风或火山气体停运，现场查运行状态。"),i("17:00｜温泉旅馆","不要晚于晚餐规定时间抵达；会席通常 18:00 前后开始。")],transport:[i("京都 → 小田原 新干线","SmartEX 最早可提前 1 年受理；实际列车座位通常按规则开放。选 Hikari 并核对是否直达小田原。","must","https://global.jr-central.co.jp/en/onlinebooking/contents/shinkansen/","SmartEX 官方"),i("箱根周游券（小田原出发）","覆盖登山电车、缆车、空中缆车、海盗船与指定巴士；线上 / 现场可购，提前 1 个月。","recommended","https://www.hakonenavi.jp/international/en/discount_passes/free_pass","箱根官方")],luggage:[i("京都 → 东京宅急便","早上交酒店前台，指定 10/19 到达东京酒店。先确认两家酒店都可收发；保留运单。官方建议至少提前 2 天寄往住宿设施，跨区或天气可能需 3 天，因此更稳妥是 10/17 晚交件。","must","https://faq-en.kuronekoyamato.co.jp/app/answers/detail/a_id/6692/","Yamato 官方"),i("箱根只带一晚包","温泉用品通常酒店提供；带明日衣物、药物与贵重物品。")],food:[i("车站便当","京都站选一份季节便当，上车后吃。"),i("旅馆会席","确认晚餐开始时间、过敏与生食偏好；属于住宿的一部分。","must")],hotels:[i("Hyatt Regency Hakone Resort & Spa","强罗的大房间与温泉体验，适合用积分。","recommended","https://www.hyatt.com/en-US/hotel/japan/hyatt-regency-hakone-resort-and-spa/hakhr"),i("日式温泉旅馆（待定）","若更重视怀石与私人风吕，选箱根汤本 / 强罗 / 芦之湖一带。","recommended")],bookings:[i("京都→小田原","热门时段尽早锁定；>160 cm 行李需订带超大行李空间座位，但本日大箱已宅配。","must"),i("温泉酒店 + 晚餐","周日也建议尽早订并确认最晚入住时间。","must")]},
{date:"10.19",weekday:"周一",city:"箱根 → 东京",title:"芦之湖晨雾 · 回到东京",summary:"补完箱根环线后回东京，取回大箱；最后一晚把购物和告别餐安排在同一区域。",hotel:"东京 · 最后 1 晚",itinerary:[i("08:30｜箱根晨间","天气好走芦之湖 / 箱根神社；天气差去 POLA 美术馆或雕刻之森。"),i("12:00｜小田原 → 东京","东海道新干线约半小时；也可小田急回新宿。"),i("15:00｜入住与购物","银座、新宿或涩谷，按最后酒店就近安排。"),i("19:00｜告别晚餐","寿司、烧肉或你们旅途中最想再吃一次的料理。")],transport:[i("箱根 → 东京","若箱根周游券为小田原出发，则另买小田原→东京；新干线无需很早预订。","recommended","https://global.jr-central.co.jp/en/onlinebooking/","JR Central")],luggage:[i("东京酒店取回大箱","出发前 48–72 小时让京都前台确认预计到达日；贵重品、药物永远随身。")],food:[i("小田原：鱼板 / 海鲜","若时间合适，在小田原吃午餐再进东京。"),i("东京告别餐","热门寿司或烧肉务必提前；预留购物打包时间。","must")],hotels:[i("东京站 / 银座","次日乘 N’EX 去成田最直接。Hyatt Centric Ginza 或 Caption by Hyatt Kabutocho 可比较。","recommended","https://www.hyatt.com/en-US/destinations/tokyo")],bookings:[i("告别晚餐","建议 4–8 周预订。","must")]},
{date:"10.20",weekday:"周二",city:"东京 → 成田",title:"最后一碗面 · 回家",summary:"17:05 从 NRT 起飞。上午只做轻量购物和午餐，最晚约 13:00–13:30 从市区出发。",hotel:"返程日",itinerary:[i("08:30｜早餐与最后采购","东京站 / 银座范围内活动，不跨城。"),i("11:30｜早午餐","荞麦、鳗鱼饭或寿司，避开需要久候的店。"),i("13:00｜前往成田","国际航班建议至少提前 3 小时到机场，并给列车异常留缓冲。"),i("17:05｜NRT 起飞","在安检前完成退税品与托运行李整理。")],transport:[i("N’EX / Skyliner","根据最终酒店选路线；N’EX 往返票若满足 14 天有效期可比较。","recommended","https://www.jreast.co.jp/en/multi/nex/tickets/","N’EX 官方")],luggage:[i("全部随身去机场","检查宅配运单、护照、免税品封袋与充电宝位置。","none")],food:[i("机场前的最后一餐","留在市区吃，不把期待放在机场餐饮。")],hotels:[i("无住宿","")],bookings:[i("机场列车","建议前一天或更早锁定合适班次。","recommended")]}
];

export const checklist = [
 {when:"现在",date:"住宿",title:"全程酒店（尤其京都、箱根）",status:"must" as Status,note:"先锁可取消房价；箱根确认含晚餐及最晚入住时间。",link:"https://www.hyatt.com/"},
 {when:"现在",date:"餐饮",title:"京都怀石 / 割烹、东京告别餐",status:"recommended" as Status,note:"热门店通常提前 1–2 个月；可请酒店礼宾协助。",link:"https://www.tablecheck.com/en/japan"},
 {when:"已可规划",date:"10/18",title:"京都 → 小田原 SmartEX",status:"must" as Status,note:"官方支持最早提前 1 年受理；优先直达小田原的 Hikari。",link:"https://global.jr-central.co.jp/en/onlinebooking/contents/shinkansen/"},
 {when:"9/10",date:"10/10",title:"N’EX / Skyliner 进城",status:"recommended" as Status,note:"通常提前 1 个月；若担心航班延误可落地再买。",link:"https://www.jreast.co.jp/en/multi/nex/tickets/"},
 {when:"已预订",date:"10/12",title:"Azusa 新宿 → 松本｜BOOKED / CONFIRMED",status:"confirmed" as Status,note:"10:00 新宿出发，12:37 松本抵达；2 位成人，Green Reserved，总价 ¥27,560，QR voucher。08:00 从东京王子大饭店离店，目标 09:00 前进入新宿 JR 区域。",link:"https://www.jreast.co.jp/en/multi/traininformation/azusa_kaiji/index.html"},
 {when:"已预订",date:"10/13",title:"上高地私人团｜BOOKED / CONFIRMED",status:"confirmed" as Status,note:"08:00 TABINO HOTEL Lit MATSUMOTO 接送；2 位成人，英语，约 8 小时，US$373.26。Custom drop-off confirmed with vendor：在上高地巴士总站结束。后续上高地→平汤→高山公交票不包含在 tour 内，需自行购买。",link:"https://www.getyourguide.com/nagano-l5079/from-nagano-kamikochi-private-day-trip-with-pickup-t1411016/"},
 {when:"9/14",date:"10/14",title:"高山 → 白川乡 → 金泽",status:"must" as Status,note:"两段一起订，避免中间无车可走。",link:"https://www.nouhibus.co.jp/highwaybus/toyama_en/"},
 {when:"9/15",date:"10/15",title:"金泽 → 京都（敦贺换乘）",status:"must" as Status,note:"两段指定席一起购买并留意换乘站台。",link:"https://www.westjr.co.jp/global/en/howto/train-reservation/condition/"},
 {when:"9/18",date:"10/18",title:"箱根周游券",status:"recommended" as Status,note:"从小田原出发的 2 日券；也可当日购买。",link:"https://www.hakonenavi.jp/international/en/discount_passes/free_pass"},
 {when:"10/11 前",date:"行李",title:"确认东京 → 金泽宅配",status:"must" as Status,note:"确认两家酒店前台均可收发，并写入住日 / 预订号。",link:"https://faq-en.kuronekoyamato.co.jp/app/answers/detail/a_id/6074/"},
 {when:"10/17 前",date:"行李",title:"确认京都 → 东京宅配",status:"must" as Status,note:"官方提醒住宿件至少提前 2 天，远距离可能 3 天。",link:"https://faq-en.kuronekoyamato.co.jp/app/answers/detail/a_id/6692/"}
];
