"use client";
import { useEffect, useState } from "react";
import { checklist, days, Item, Status } from "./data";

const labels:Record<Status,string>={must:"提前预订",recommended:"建议预订",none:"无需预订"};
const sectionIcons:Record<string,string>={itinerary:"⌁",transport:"↗",luggage:"▣",food:"◌",hotels:"⌂",bookings:"✓"};
const sectionNames:Record<string,string>={itinerary:"行程与景点",transport:"交通物流",luggage:"行李物流",food:"美食重点",hotels:"住宿选项",bookings:"预约事项"};
const terms:[string,string][]=[
 ["成田机场","成田空港（Narita Kūkō）"],["清澄庭园","清澄庭園（Kiyosumi Teien）"],["筑地场外","築地場外市場（Tsukiji Jōgai Shijō）"],["近江町市场","近江町市場（Ōmichō Ichiba）"],["宫川朝市","宮川朝市（Miyagawa Asaichi）"],["日本阿尔卑斯","日本アルプス（Nihon Arupusu）"],["上高地线","上高地線（Kamikōchi-sen）"],["松本城","松本城（Matsumoto-jō）"],["中町通","中町通り（Nakamachi-dōri）"],["绳手通","縄手通り（Nawate-dōri）"],["大正池","大正池（Taishō-ike）"],["河童桥","河童橋（Kappabashi）"],["平汤","平湯（Hirayu）"],["白川乡","白川郷（Shirakawa-gō）"],["兼六园","兼六園（Kenroku-en）"],["金泽城","金沢城（Kanazawa-jō）"],["鸭川","鴨川（Kamo-gawa）"],["先斗町","先斗町（Pontochō）"],["清水寺","清水寺（Kiyomizu-dera）"],["三年坂","産寧坂（Sannen-zaka）"],["二年坂","二寧坂（Ninen-zaka）"],["高台寺","高台寺（Kōdai-ji）"],["建仁寺","建仁寺（Kennin-ji）"],["祇园","祇園（Gion）"],["春日大社","春日大社（Kasuga Taisha）"],["奈良公园","奈良公園（Nara Kōen）"],["东大寺","東大寺（Tōdai-ji）"],["芦之湖","芦ノ湖（Ashi-no-ko）"],["大涌谷","大涌谷（Ōwakudani）"],["箱根神社","箱根神社（Hakone Jinja）"],["雕刻之森","彫刻の森美術館（Chōkoku-no-Mori Bijutsukan）"],["新岛々","新島々（Shin-Shimashima）"],["成田","成田（Narita）"],["东京","東京（Tokyo）"],["松本","松本（Matsumoto）"],["上高地","上高地（Kamikōchi）"],["高山","高山（Takayama）"],["金泽","金沢（Kanazawa）"],["京都","京都（Kyoto）"],["奈良","奈良（Nara）"],["箱根","箱根（Hakone）"],["小田原","小田原（Odawara）"],["强罗","強羅（Gōra）"],["浅草寺","浅草寺（Sensō-ji）"],["合羽桥","かっぱ橋（Kappabashi）"],["人形町","人形町（Ningyōchō）"],["银座","銀座（Ginza）"],["新宿","新宿（Shinjuku）"],["有乐町","有楽町（Yūrakuchō）"],["思出横丁","思い出横丁（Omoide Yokochō）"],
 ["飞驒牛握寿司","飛騨牛握り寿司（Hida-gyū nigiri-zushi）"],["飞驒牛","飛騨牛（Hida-gyū）"],["飞驒","飛騨（Hida）"],["信州","信州（Shinshū）"],["北陆","北陸（Hokuriku）"],["朴叶味噌","朴葉味噌（Hōba miso）"],["山贼烧","山賊焼き（Sanzoku-yaki）"],["山葵","わさび（Wasabi）"],["信州荞麦","信州そば（Shinshū soba）"],["荞麦","そば（Soba）"],["江户前寿司","江戸前寿司（Edomae-zushi）"],["寿司","寿司（Sushi）"],["天妇罗","天ぷら（Tempura）"],["鳗鱼饭","うな重（Unajū）"],["鳗鱼","鰻（Unagi）"],["寿喜烧","すき焼き（Sukiyaki）"],["烧鸟","焼き鳥（Yakitori）"],["刺身","刺身（Sashimi）"],["关东煮","おでん（Oden）"],["拉面","ラーメン（Rāmen）"],["玉子烧","玉子焼き（Tamagoyaki）"],["怀石","懐石料理（Kaiseki ryōri）"],["割烹","割烹（Kappō）"],["汤豆腐","湯豆腐（Yudōfu）"],["京野菜","京野菜（Kyō-yasai）"],["柿叶寿司","柿の葉寿司（Kaki-no-ha-zushi）"],["葛料理","葛料理（Kuzu ryōri）"],["茶粥","茶粥（Chagayu）"],["釜饭","釜飯（Kamameshi）"],["海鲜丼","海鮮丼（Kaisen-don）"],["甘虾","甘えび（Ama-ebi）"],["喉黑鱼","のどぐろ（Nodoguro）"],["加贺蔬菜","加賀野菜（Kaga yasai）"],["鱼板","蒲鉾（Kamaboko）"],["会席","会席料理（Kaiseki ryōri）"],["清酒","日本酒（Nihonshu）"],["味噌","味噌（Miso）"],["居酒屋","居酒屋（Izakaya）"]
];
const termMap=new Map(terms);
const termPattern=new RegExp(terms.map(([from])=>from.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|"),"g");
const jp=(text:string)=>text.replace(termPattern,match=>termMap.get(match)||match);
function Badge({status}:{status?:Status}){return status?<span className={`badge ${status}`}>{labels[status]}</span>:null}
function ItemCard({item}:{item:Item}){return <article className="item"><div className="itemTop"><h4>{jp(item.title)}</h4><Badge status={item.status}/></div><p>{jp(item.detail)}</p>{item.link&&<a href={item.link} target="_blank" rel="noreferrer">{item.linkLabel||"打开官网"} <span>↗</span></a>}</article>}
function Section({name,items,open,onToggle}:{name:string;items:Item[];open:boolean;onToggle:()=>void}){return <section className={`fold ${open?"open":""}`}><button className="foldHead" onClick={onToggle} aria-expanded={open}><span className="foldIcon">{sectionIcons[name]}</span><b>{sectionNames[name]}</b><span className="count">{items.length}</span><span className="chev">⌄</span></button>{open&&<div className="items">{items.map((x,n)=><ItemCard key={n} item={x}/>)}</div>}</section>}

export default function Home(){
 const [view,setView]=useState<"days"|"bookings"|"guide">("days"); const [selected,setSelected]=useState(0);
 const [open,setOpen]=useState<Record<string,boolean>>({itinerary:true,transport:true,bookings:true}); const [done,setDone]=useState<number[]>([]);
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("jp-bookings")||"[]"))}catch{}},[]);
 const toggleDone=(n:number)=>{const next=done.includes(n)?done.filter(x=>x!==n):[...done,n];setDone(next);localStorage.setItem("jp-bookings",JSON.stringify(next))}; const day=days[selected];
 return <main>
  <header className="hero"><nav><span className="brand"><i/>日本 · 十月</span><span>10 晚 · 11 天</span></nav><div className="heroInner"><div className="eyebrow">OCTOBER 10—20, 2026</div><h1>从東京（Tokyo）的烟火气，<br/>走进日本アルプス（Nihon Arupusu）的秋。</h1><p className="lede">成田（Narita） → 東京（Tokyo） → 松本（Matsumoto） → 上高地（Kamikōchi） → 高山（Takayama） → 白川郷（Shirakawa-gō） → 金沢（Kanazawa） → 京都（Kyoto） / 奈良（Nara） → 箱根（Hakone） → 東京（Tokyo）</p><div className="heroStats"><div><b>11</b><span>天</span></div><div><b>9</b><span>目的地</span></div><div><b>2</b><span>次行李宅配</span></div><div><b>6</b><span>地方风味</span></div></div></div><div className="stamp">秋<br/><small>二〇二六</small></div></header>
  <div className="tabs"><button className={view==="days"?"active":""} onClick={()=>setView("days")}>逐日行程</button><button className={view==="bookings"?"active":""} onClick={()=>setView("bookings")}>预约清单 <em>{checklist.filter((_,n)=>!done.includes(n)).length}</em></button><button className={view==="guide"?"active":""} onClick={()=>setView("guide")}>旅途指南</button><button className="print" onClick={()=>window.print()}>打印 / PDF</button></div>
  {view==="days"&&<><div className="dayRail" aria-label="选择日期">{days.map((d,n)=><button key={d.date} className={n===selected?"active":""} onClick={()=>{setSelected(n);scrollTo({top:430,behavior:"smooth"})}}><small>D{String(n+1).padStart(2,"0")}</small><b>{d.date}</b><span>{jp(d.city)}</span></button>)}</div><section className="dayWrap"><div className="dayTitle"><div><small>DAY {String(selected+1).padStart(2,"0")} · {day.weekday.toUpperCase()}</small><h2>{jp(day.title)}</h2><p>{jp(day.summary)}</p><span className="night">⌂ {jp(day.hotel)}</span></div><div className="bigDate">{day.date}</div></div><div className="sections">{(["itinerary","transport","luggage","food","hotels","bookings"] as const).map(name=><Section key={name} name={name} items={day[name]} open={!!open[name]} onToggle={()=>setOpen({...open,[name]:!open[name]})}/>)}</div><div className="next"><button disabled={selected===0} onClick={()=>setSelected(selected-1)}>← 前一天</button><span>{selected+1} / {days.length}</span><button disabled={selected===days.length-1} onClick={()=>setSelected(selected+1)}>后一天 →</button></div></section></>}
  {view==="bookings"&&<section className="content"><div className="viewHead"><small>RESERVATION DESK</small><h2>预约清单</h2><p>按开放日期排序。勾选状态只保存在你的这台设备上。</p><div className="progress"><span style={{width:`${done.length/checklist.length*100}%`}}/><b>{done.length} / {checklist.length} 已完成</b></div></div><div className="checklist">{checklist.map((x,n)=><article className={done.includes(n)?"done":""} key={x.title}><button onClick={()=>toggleDone(n)} aria-label={done.includes(n)?"标记未完成":"标记完成"}>{done.includes(n)?"✓":""}</button><div className="checkWhen"><b>{x.when}</b><span>{x.date}</span></div><div className="checkMain"><Badge status={x.status}/><h3>{jp(x.title)}</h3><p>{jp(x.note)}</p></div><a href={x.link} target="_blank" rel="noreferrer">预订官网 ↗</a></article>)}</div><aside className="notice"><b>预约窗口说明</b><p>“提前 1 个月”通常是同日前一个月日本时间开放，但运营方可能调整。2026 秋季详细时刻、临时停运和价格仍应在购票当天以官网为准；本站把官方入口集中好了。</p></aside></section>}
  {view==="guide"&&<section className="content"><div className="viewHead"><small>TRIP FIELD NOTES</small><h2>旅途指南</h2><p>三条主线：吃得有地域感、转场不拖大箱、每天留一点呼吸。</p></div><div className="guideGrid"><article><span>01</span><h3>行李路线</h3><p><b>人：</b>{jp("东京 → 松本 → 上高地 → 高山 → 白川乡 → 金泽 → 京都 → 箱根 → 东京")}</p><p><b>大箱：</b>{jp("东京 ─→ 金泽；京都 ─→ 东京")}</p><p>酒店互寄前确认两端前台可收发。运单写姓名、入住日期、酒店电话和预订号；保留照片与追踪号。Yamato 提醒住宿件至少提前 2 天交运，远距离可能需 3 天。</p><a href="https://www.global-yamato.com/en/hands-free-travel/" target="_blank" rel="noreferrer">Yamato 指南 ↗</a></article><article><span>02</span><h3>一条风味地图</h3><ul><li>{jp("东京｜江户前寿司、天妇罗、鳗鱼")}</li><li>{jp("信州｜荞麦、山葵、山贼烧")}</li><li>{jp("飞驒｜飞驒牛、朴叶味噌")}</li><li>{jp("北陆｜甘虾、喉黑鱼、加贺蔬菜")}</li><li>{jp("京都｜怀石、汤豆腐、京野菜")}</li><li>{jp("箱根｜温泉会席、小田原鱼板")}</li></ul></article><article><span>03</span><h3>交通判断</h3><p>这个路线通常不需要全国 JR Pass。把高速巴士、Azusa、JR-WEST 北陆段和 SmartEX 分开预订更清楚。</p><p>东海道新干线若携带三边合计 <b>161–250 cm</b> 的箱子，必须预约带超大行李空间座位；本方案在{jp("京都→箱根")}前已把大箱宅配。</p><a href="https://global.jr-central.co.jp/en/info/oversized-baggage/" target="_blank" rel="noreferrer">大件行李规则 ↗</a></article><article><span>04</span><h3>十月山地装备</h3><p>{jp("东京与京都可能温和，上高地早晚则明显冷。用三层法：速干内层、抓绒 / 薄羽绒、防风防雨外层。带防滑步行鞋、小折伞、移动电源与少量现金。")}</p><p>{jp("上高地遇持续雨、强风或巴士异常时，直接缩短徒步，优先保住转往高山的班次。")}</p></article></div><div className="sources"><h3>关键官方入口</h3><a href="https://www.jreast.co.jp/en/multi/" target="_blank">JR East</a><a href="https://visit-nagano.alpico.co.jp/" target="_blank">ALPICO</a><a href="https://www.nouhibus.co.jp/english/" target="_blank">浓飞巴士</a><a href="https://www.westjr.co.jp/global/en/" target="_blank">JR West</a><a href="https://global.jr-central.co.jp/en/" target="_blank">JR Central</a><a href="https://www.hakonenavi.jp/international/en/" target="_blank">箱根（Hakone）官方</a></div></section>}
  <footer><span>JAPAN · AUTUMN 2026</span><p>最后核对：2026 年 9 月 · 所有时刻与票价以运营方最新公告为准</p></footer>
 </main>
}
